### ISSUE TITLE
Unprocessable entity error 

### ISSUE THREAD

**Issue by 1blackbar** [sddebz/stable-diffusion-krita-plugin#2]
I got this after i reran the model, what does it mean ?
I cant fix thins in any way, uninstaling /reinstaling doesnt help, i think some leftover files create conflict or lack of some files

...OK i managed to make it work again, wiped eveyrthing , plugin difectory in krita resources too, then reinstalled, so far its fine but no idea whats caused this

I suspect it might be  problem with merging that new fork with prompting in krita and yours.. cant mix both

making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
INFO:     Started server process [12808]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
src path: D:\stabk\krita\input\1661869151.png
INFO:     127.0.0.1:11793 - "GET /config HTTP/1.1" 200 OK
INFO:     127.0.0.1:11794 - "GET /txt2img?orig_width=409&orig_height=572 HTTP/1.1" 422 Unprocessable Entity
src path: D:\stabk\krita\input\1661869220.png
INFO:     127.0.0.1:11796 - "GET /config HTTP/1.1" 200 OK
INFO:     127.0.0.1:11797 - "GET /txt2img?orig_width=217&orig_height=329 HTTP/1.1" 422 Unprocessable Entity

**Comment by sddebz** [comment]
I think this error means server wants different query parameters from what plugin sent. Maybe there was a mismatch between plugin and server versions.

**Comment by 1blackbar** [comment]
IT was when i was messing around with that inkrita prompt box, i uninstlled it tho cause it got annoying pretty fast , separate text file is better to work with unless theres a proper panel in krita but its already too cluttered so its great like it is now, i like all settings available, somehow it also succeeds to produce high res images without cloning the subject that often
