### ISSUE TITLE
Full Resolution Inpainting

### ISSUE THREAD

**Issue by ninjasaid2k** [sddebz/stable-diffusion-krita-plugin#44]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm inpainting, the inpainted area just made it blurrier than the original.

**Describe the solution you'd like**
I'm trying out inpainting in Krita but it's not as good as inpainting in Automatic1111 inpainting where it has an option for full resolution inpainting.

**Describe alternatives you've considered**
I've tried messing with other settings such as CFG values and denoising strength but it's not appearing to get better.

**Comment by Interpause** [comment]
I fixed it in my fork, https://github.com/Interpause/auto-sd-krita, which I have also been keeping up to date with AUTOMATIC1111. So newer features like the new prompt weighing syntax and compositional diffusion via "AND" works.
