### ISSUE TITLE
NEw version wont work here, nothig was changed, no plugin in tools-scripts(solved)

### ISSUE THREAD

**Issue by 1blackbar** [sddebz/stable-diffusion-krita-plugin#5]
solved, i moved it to new location where my other webuis are

Also i see that the thing with slowing down when resynthesizing is partially solved but still happens, i mark my region with rectangle marquee and synthesize, got resut  and when i synthesize again it fallsback into slow mode

**Comment by sddebz** [comment]
Nice it was solved. I should probably add to instructions that you need install this repo separately, because there are breaking changes in webui repo frequently.
